### ISSUE TITLE
Requirements for loot entries and pools

### ISSUE THREAD

**Issue by Archy-X** [Archy-X/AuraSkills#372]
### Feature description

Extend the requirements system to enable adding requirements (such as skill levels) for obtaining specific loot entries and/or loot pools. If the player does not meet the requirements for a loot entry/pool, it is ignored in loot selection.

## Details

Core features:
- Single requirements on a loot entry (excludes the item/loot if not met)
- Single requirements on a loot pool (excludes the entire loot pool if not met)
- Multiple requirements on a loot entry/pool that must all be met
- Multiple types of requirements, including skill levels, stat levels, permissions, and worlds

Possible additions:
- A permission to bypass loot requirements
- Requirements for an entire loot table file (all pools)

## Implementation

This implementation should reuse the `RequirementNode` class and subclasses used for block requirements. Loading requirements for loot entries can be added in `LootParsingContextImpl` and requirements for pools can be added in `LootLoader`. Both places should call common code for loading a list of loot requirements (pass `List<ConfigurationNode>`). Implementing checking loot requirements can be done in LootHandler and its subclasses (BlockLootHandler, etc).

## Configuration

Example config for requirements on a loot pool:
```yaml
pools:
  rare:
    base_chance: 0
    selection_priority: 1
    requirements:
    - type: skill_level
      skill: farming
      level: 10
    - type: permission
      permission: some.permission.node
    loot: []
```

Example config for requirements on a loot entry.
```yaml
pools:
  rare:
    base_chance: 0
    selection_priority: 1
    loot:
    - type: item
      material: stick
      weight: 10
      amount: 1-2
      xp: 20
      requirements:
      - type: skill_level
        skill: farming
        level: 10
      - type: permission
        permission: some.permission.node
```
