### ISSUE TITLE
Loot with chance based enchantment(s)

### ISSUE THREAD

**Issue by MC-MrBirdy** [Archy-X/AuraSkills#380]
### Feature description

Using a minimum level of 0 will allow enchantments to be rolled but not applied. This however doesn't allow enchantments to be setup as a rare enchantment. Adding support for something like a chance based setting, per enchantment, could offer more randomized loot with the option for rare enchantments.

E.g.
The following loot often seems to roll with many of the listed enchantments, even if an enchantment like soul speed would be preferred to be very rare.
```yml
- type: item
        material: netherite_boots
        weight: 1
        amount: 1
        enchantments:
        - 'protection 0-4'
        - 'soul_speed 0-3'
        - 'mending 0-1'
```

Allowing a chance (double) after the levels could allow for such a setup.
```yml
- type: item
        material: netherite_boots
        weight: 1
        amount: 1
        enchantments:
        - 'protection 0-4 0.75'
        - 'soul_speed 0-3 0.1'
        - 'mending 0-1 0.5'
```

### Additional context

A rough example of this being implemented:

bukkit\src\main\java\dev\aurelium\auraskills\bukkit\loot\item\enchant\LootEnchantEntry.java ;
```diff
package dev.aurelium.auraskills.bukkit.loot.item.enchant;

- public record LootEnchantEntry(String enchantName, int minLevel, int maxLevel) {
+ public record LootEnchantEntry(String enchantName, int minLevel, int maxLevel, double chance) {

}
```

bukkit\src\main\java\dev\aurelium\auraskills\bukkit\loot\item\enchant\LootEnchantList.java ;
```diff
        List<LeveledEnchant> rolled = new ArrayList<>();
        for (LootEnchantEntry entry : entries) {
            Enchantment enchantment = Registry.ENCHANTMENT.get(NamespacedKey.minecraft(entry.enchantName().toLowerCase(Locale.ROOT)));
+			// Avoid getting a random double if the chance is 1.0
+			double chance = 1.0;
+			if (entry.chance() < 1.0)
+			{
+				chance = ThreadLocalRandom.current().nextDouble(0.0, 1.0);
+			}
            if (enchantment != null) {
-                int rolledLevel = ThreadLocalRandom.current().nextInt(entry.minLevel(), entry.maxLevel() + 1);
-                rolled.add(new LeveledEnchant(enchantment, rolledLevel));
+				if (chance <= entry.chance())
+				{
+					int rolledLevel = ThreadLocalRandom.current().nextInt(entry.minLevel(), entry.maxLevel() + 1);
+					rolled.add(new LeveledEnchant(enchantment, rolledLevel));
+				}
            } else {
                plugin.logger().warn("Error while rolling enchant in loot table " + table.getId() + ": " +
                        "Could not find enchantment in Minecraft registry with key " + entry.enchantName());
```

bukkit\src\main\java\dev\aurelium\auraskills\bukkit\loot\parser\ItemLootParser.java ;
```diff
            String enchantmentName = splitEntry[0].toLowerCase(Locale.ROOT);
            int minLevel = 1;
            int maxLevel = 1;
+            double chance = 1.0;
...
                    maxLevel = fixedLevel;
                }
            }
-            LootEnchantEntry entry = new LootEnchantEntry(enchantmentName, minLevel, maxLevel);
+            if (splitEntry.length > 2) {
+                chance = Double.parseDouble(splitEntry[2]);
+            }
+            LootEnchantEntry entry = new LootEnchantEntry(enchantmentName, minLevel, maxLevel, chance);
            entryList.add(entry);
        }
        return new LootEnchantList(entryList);
```
