### ISSUE TITLE
Ability to set different loot tables for different worlds

### ISSUE THREAD

**Issue by IAmSoccer** [Archy-X/AuraSkills#82]
### Feature description

Make it possible to setup different loot tables for different worlds. I don't really know how to explain it further, as all it is, is per-world support for loot tables in the "loot" folder.

### Additional context

Configuration example

```
pools:
  mainpool: #Effects all worlds/regions unless disabled
  enabled: true #if false, only per-world loot tables will work. If true, affects all worlds and per-world loot tables are disabled
    rare:
      base_chance: 3
      selection_priority: 1
      loot:
        - type: item
          material: iron_ingot
          weight: 15
          amount: 1
    epic:
      base_chance: 2
      selection_priority: 1
      loot:
        - type: item
          material: gold_ingot
          weight: 10
          amount: 1
  exampleworldpool:
  world: exampleworld
    rare:
      base_chance: 3
      selection_priority: 1
      loot:
        - type: item
          material: iron_ingot
          weight: 15
          amount: 1
    epic:
      base_chance: 2
      selection_priority: 1
      loot:
        - type: item
          material: diamond
          weight: 10
          amount: 1
```
